### ISSUE TITLE
How do we use this pipeline?

### ISSUE THREAD

**Issue by YichaoOU** [gifford-lab/inDelphi-dataprocessinganalysis#2]
The documentation is poor and unclear about how to use this pipeline. Does this pipeline require installation? Can you show some example code? 

My suggestion is to follow some good practice, e.g., [example1](https://github.com/jehna/readme-best-practices.)

Thanks,
Yichao

**Comment by maxwshen** [comment]
Hi Yichao,

Thanks for the feedback. We anticipated that it would be highly unlikely for scientists to produce data using the same library assay structure that we used for this project, and indeed, there are zero reports of anyone attempting to generate new data following our library design protocol. I do note that there are several other papers published at this point that use large-scale libraries to study this problem, but their experiment designs are different than ours, and therefore require different data processing approaches. For example, we found it to be crucial to handle sgRNA-target site recombination in our data, but other library assay designs have been developed that address recombination in the protocol. Due to the unlikely nature of other groups producing similar datasets, we intended this github repository to act as documentation of how our data was processed, but not as a pipeline for people to use to process their own data.

We anticipated that it would be more convenient for most users to simply provide them with the final processed data, which are available at the figshare links in our paper. We note that many computational biology papers only provide the raw data that requires manual processing, so we thought that taking the extra effort to provide the processed data would be appreciated by the community.

Best,
Max
